[package]
name = "flag"
version = "0.0.0"
authors = ["Flagship Team"]
edition = "2018"

[features]
default = ["swizzle"]
swizzle = ["vec2-swizzle", "vec3-swizzle", "vec4-swizzle"]
vec2-swizzle = []
vec3-swizzle = []
vec4-swizzle = []